db.mysql.servicename: mysql_cli

cloud:
  aws:
    s3:
      bucket: springboot-paasta
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: AKIAQDEDZTCHLGGOORN4
      secret-key: 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
      instanceprofile: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:${vcap.services.mysql_cli.credentials.uri}?serverTimezone=UTC&verifyServerCertificate=false&useSSL=false&requireSSL=false&useUnicode=true&characterEncoding=utf8
    username: ${vcap.services.mysql_cli.credentials.username}
    password: ${vcap.services.mysql_cli.credentials.password}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  messages:
    basename: errors
  cloud:
    refresh:
      extra-refreshable: javax.sql.DataSource

logging:
  level:
    #    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  servlet:
    session:
      tracking-modes: cookie

#project:
#  basedir: spring/paasta

#file:
#  dir: C:/${project.basedir}/2021_Paas_Ta/Paas_Ta_Front/paas/public/img/
#file.dir: https://onnuriservice1.paas-ta.org/img/