db.mysql.servicename: mysql_cli

spring:
  datasource:
    url: jdbc:${vcap.services.mysql_cli.credentials.uri}
    username: ${vcap.services.mysql_cli.credentials.username}
    password: ${vcap.services.mysql_cli.credentials.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: errors

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  servlet:
    session:
      tracking-modes: cookie

project:
  basedir: spring/paasta

file:
  dir: C:/${project.basedir}/2021_Pasas_Ta/Paas_Ta_Front/paas/public/img/