db.mysql.servicename: mysql_cli

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:${vcap.services.mysql_cli.credentials.uri}?serverTimezone=UTC&verifyServerCertificate=false&useSSL=false&requireSSL=false&useUnicode=true&characterEncoding=utf8
    username: ${vcap.services.mysql_cli.credentials.username}
    password: ${vcap.services.mysql_cli.credentials.password}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  messages:
    basename: errors
  cloud:
    refresh:
      extra-refreshable: javax.sql.DataSource

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  servlet:
    session:
      tracking-modes: cookie

project:
  basedir: spring/paasta

file:
  dir: C:/${project.basedir}/2021_Paas_Ta/Paas_Ta_Front/paas/public/img/